# (Optional) Set Google Analytics if you use it to track your website.
# Always put it on the top of the configuration file, otherwise it won't work
googleAnalytics = "G-BJBD0VKKMG"

baseURL = 'https://docs.exray.dev/'
languageCode = 'en-us'
title = 'Side-Eye Debugger'

[deployment]

[[deployment.targets]]
# An arbitrary name for this target.
URL = "s3://exray-docs?region=us-east-2"
name = "production"

cloudFrontDistributionID = "E4IHFWYQPQOHX"

[params]
BookSection = '*'
# (Optional, default favicon.png) Set the path to a favicon file.
# If the favicon is /static/favicon.png then the path would be favicon.png
BookFavicon = 'favicon.svg'
BookTheme = 'dark'
